name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to VPS via rsync
        uses: appleboy/rsync-action@v0.0.8
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          src: 'build/'
          dest: '/home/SanderSita/web/sandersekreve.nl/public_html/'
          args: -avz --delete
